Repository adobe/asset-share-commons, pull requests merged in 2018-03, with the labels that each got.

#150 Feature/149
  core/src/main/java/com/adobe/aem/commons/assetshare/content/MetadataProperties.java
  core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/MetadataSchemaPropertiesImpl.java
  core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/datasources/MetadataSchemaPropertiesDataSource.java
Labels: bug

#155 #154 fix to sling script helper/bindings issue
  core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
Labels: aem 6.4

#160 removed contexthub segment on en page
  ui.content/src/main/content/jcr_root/content/asset-share-commons/en/.content.xml
Labels: aem 6.4, bug
